base:
  alternative_bold_font: ./fonts/Roboto-Medium.ttf
  alternative_font: ./fonts/Roboto-Regular.ttf
  artist: Vincent Ch1n
  bold_font: ./fonts/AlibabaPuHuiTi-2-85-Bold.otf
  bold_font_size: 1
  font: ./fonts/AlibabaPuHuiTi-2-45-Light.otf
  font_size: 1
  input_dir: "/Users/vincent/Pictures/\u5F85\u5904\u7406/Input"
  output_dir: "/Users/vincent/Pictures/\u5F85\u5904\u7406/Output"
  quality: 100
global:
  focal_length:
    use_equivalent_focal_length: false
  padding_with_original_ratio:
    enable: false
  shadow:
    enable: false
  white_margin:
    enable: true
    width: 1
layout:
  background_color: '#ffffff'
  elements:
    left_bottom:
      color: '#757575'
      is_bold: false
      name: Param
    left_top:
      color: '#757575'
      is_bold: false
      name: LensMake_LensModel
    right_bottom:
      color: '#757575'
      is_bold: false
      name: Custom
      value: Vincent Ch1n
    right_top:
      color: '#757575'
      is_bold: false
      name: GeoInfo
  logo_enable: true
  logo_position: left
  type: watermark_right_logo
logo:
  default:
    id: ''
    path: ./logos/icon.png
  makes:
    apple:
      id: APPLE
      path: ./logos/icon.png
    canon:
      id: Canon
      path: ./logos/icon.png
    dji:
      id: DJI
      path: ./logos/icon.jpg
    empty:
      id: "\u7A7A"
      path: ./logos/icon.png
    fujifilm:
      id: FUJIFILM
      path: ./logos/icon.png
    hasselblad:
      id: HASSELBLAD
      path: ./logos/icon.png
    huawei:
      id: HUAWEI
      path: ./logos/icon.png
    leica:
      id: leica
      path: ./logos/icon.png
    nikon:
      id: NIKON
      path: ./logos/icon.png
    olympus:
      id: Olympus
      path: ./logos/icon.png
    panasonic:
      id: Panasonic
      path: ./logos/icon.png
    pentax:
      id: PENTAX
      path: ./logos/icon.png
    ricoh:
      id: RICOH
      path: ./logos/icon.png
    sony:
      id: SONY
      path: ./logos/icon.png
